name: "\U0001F41B Website Bug Report"
description: Report an issue or possible bug with the WEBSITE for The Bag 👜✨. Please report issues for the npm package on the astro-vtbot Library Repository, see link three lines below.
labels: []
assignees: []
body:
  - type: textarea
    id: bug-description
    attributes:
      label: Describe the Bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    id: bug-expectation
    attributes:
      label: What's the expected result?
      description: Describe what you expect to happen.
    validations:
      required: true
  - type: checkboxes
    id: will-pr
    attributes:
      label: Participation
      options:
        - label:  I am willing to submit a pull request for this issue.
          required: false
