blank_issues_enabled: false
contact_links:
  - name: astro-vtbot Library Repository
    url: https://github.com/martrapp/astro-vtbot
    about: You are in the repository of the WEBSITE for The Bag 👜✨. Is your problem, query or discussion related to the astro-vtbot library rather than the website? Then please visit the library repository by clicking the button on the right.
  - name: GitHub Discussions
    url: https://github.com/martrapp/astro-vtbot/discussions
    about: Does the issue involve a lot of explanation, or are you not sure how it can be split into actionable tasks? Consider starting a discussion on the astro-vtbot repository first.
